version: "3.3"
services:
  front-envoy:
    image: iremarkconsulting.azurecr.io/emulator_envoy:2.2
    container_name: emulator_envoy
    networks:
      - envoymesh
    expose:
      - "8080"
      - "8001"
      - "8443"
    ports:
      - "80:8080"
      - "443:8443"
      - "8001:8001"
    restart: unless-stopped

  emulator:
    image: iremarkconsulting.azurecr.io/emulator_emulator:2.2
    container_name: emulator_emulator
    networks:
      envoymesh:
        aliases:
          - emulator
    devices: [/dev/kvm]
    shm_size: 128M
    expose:
      - "8554"
    restart: unless-stopped

  jwt_signer:
    image: iremarkconsulting.azurecr.io/emulator_jwt_signer:2.2
    container_name: emulator_jwt_signer
    networks:
      envoymesh:
        aliases:
          - jwt_signer
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: iremarkconsulting.azurecr.io/emulator_nginx:2.2
    container_name: emulator_nginx
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - "80"
    restart: unless-stopped

networks:
  envoymesh: {}
